### ISSUE TITLE
Work with classes in the default package

### ISSUE THREAD

**Issue by georgelemental** [talsma-ict/umldoclet#107]
When running the doclet on classes within the default package, the below error occurs:

```
javadoc: error - fatal error encountered: java.lang.IllegalArgumentException: Package name is empty.
javadoc: error - Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.IllegalArgumentException: Package name is empty.
	at nl.talsmasoftware.umldoclet.uml.Namespace.<init>(Namespace.java:36)
	at nl.talsmasoftware.umldoclet.javadoc.UMLFactory.createPackage(UMLFactory.java:504)
	at nl.talsmasoftware.umldoclet.javadoc.UMLFactory.createPackageDiagram(UMLFactory.java:144)
	at nl.talsmasoftware.umldoclet.UMLDoclet.mapToDiagram(UMLDoclet.java:147)
	at nl.talsmasoftware.umldoclet.UMLDoclet.lambda$generatePlantUMLContent$0(UMLDoclet.java:112)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at nl.talsmasoftware.umldoclet.UMLDoclet.run(UMLDoclet.java:97)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
2 errors
```

**Comment by sjoerdtalsma** [comment]
Thank you for discovering and reporting this!

I will have a look in a week or so when I’m back from my vacation.
