### ISSUE TITLE
Bug: prefix string too short

### ISSUE THREAD

**Issue by sjoerdtalsma** [talsma-ict/umldoclet#134]
## Expected Behavior

UML and Javadoc creation without problems.

## Actual Behavior

```log
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-uml-to-javadocs) on project medewerker-authenticatie-infrastructure: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - Unanticipated error post-processing HTML: java.lang.IllegalArgumentException: Prefix string too short
[ERROR] java.lang.IllegalArgumentException: Prefix string too short
[ERROR]         at java.io.File.createTempFile(File.java:2001)
[ERROR]         at java.io.File.createTempFile(File.java:2070)
[ERROR]         at nl.talsmasoftware.umldoclet.html.HtmlFile.createNewTempFile(HtmlFile.java:81)

```

## Steps to Reproduce the Problem

  1. Create javadoc
  2. Last-processed HTML file name was: `Eq.html`

## Specifications

  - Version: `1.1.2`
  - Platform: Windows
  - Java version: `jdk1.8.0_131`

**Comment by sjoerdtalsma** [comment]
Just tested and the problem does not occur in version `1.1.1` with the same code base.  
It's very likely that this bug may therefore be related to 2d8a72f942b0e85fd643f2008744afb1255df6bc
