### ISSUE TITLE
java.lang.IllegalStateException: Cannot find color

### ISSUE THREAD

**Issue by bmhm** [talsma-ict/umldoclet#218]
## Expected Behavior

Generate SVGs

## Actual Behavior

Some SVGs are replaced by this text:
```java
An error has occured : java.lang.IllegalStateException: Cannot find color #000005
Success consists of going from failure to failure without loss of enthusiasm
Diagram size: 146 lines / 5806 characters.
PlantUML (1.2019.12) cannot parse result from dot/GraphViz.
GraphViz version used : version 2.40.1 (20161225.0304)
Please go to http://plantuml.com/graphviz-dot to check your GraphViz version.


Java Runtime: OpenJDK Runtime Environment
JVM: Eclipse OpenJ9 VM
Java Version: 11.0.4+11
Operating System: Linux
Default Encoding: ANSI_X3.4-1968
Language: en
Country: US
Machine: D100STUL0861
PLANTUML_LIMIT_SIZE: 4096
Processors: 32

java.lang.IllegalStateException: Cannot find color #000005
net.sourceforge.plantuml.svek.DotStringFactory.getClusterIndex(DotStringFactory.java:452)
net.sourceforge.plantuml.svek.DotStringFactory.solve(DotStringFactory.java:422)
net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:412)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:100)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:66)
net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:427)
net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:179)
net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:196)
net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:130)
net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:153)
net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:125)
nl.talsmasoftware.umldoclet.uml.Diagram.renderDiagramFile(Diagram.java:169)
nl.talsmasoftware.umldoclet.uml.Diagram.render(Diagram.java:129)
nl.talsmasoftware.umldoclet.UMLDoclet$$Lambda$318.00000000D03B2DF0.accept(Unknown Source)
java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$319.00000000D03B3080.accept(Unknown Source)
java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:739)
java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
nl.talsmasoftware.umldoclet.UMLDoclet.run(UMLDoclet.java:130)
jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582)
jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431)
jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
```

## Steps to Reproduce the Problem

  1. Execute javadoc:jar

## Specifications

  - Version: 2.0.6
  - GraphViz Version: 2.40.1
  - Platform: Linux
  - Java version: adaptopenjdk-openj9 @ 11.1.0-4 compiling to release=8
  - (If open source) Project link: not OSS

## speculations

* So maybe: Docs say to use a `1.x` version if you are on java 8. I use jdk11 to compile my java 8 code so I go for… `2.x`??
* I compiled graphviz myself. Does UMLDoclet / PlantUML need some "special" enablements when using `--configure`?

**Comment by bmhm** [comment]
Oh, on the PlantUML page  they say:

> If you compile Graphviz by yourself, you have to build it with libexpat in order to work with PlantUML.

Source: http://plantuml.com/graphviz-dot

**Comment by sjoerdtalsma** [comment]
> Still, some images are generated, which is confusing. I'll recompile graphviz_dot and see what happens.

Please do and it would be great if you could post the outcome here.

PlantUML is great, however 90% of the questions I get about UML Doclet are about the Graphviz dependency from PlantUML unfortunately.

**Comment by sjoerdtalsma** [comment]
By the way; to answer your original question:
> So maybe: Docs say to use a 1.x version if you are on java 8. I use jdk11 to compile my java 8 code so I go for… 2.x??

Please use 2.x when _running_ with javadoc `>=9`. Only use 1.x for javadoc `<9`

**Comment by bmhm** [comment]
> Please do and it would be great if you could post the outcome here.

Yes, it works like a charm now.

> Please use 2.x when running with javadoc >=9

Luckily I did. Maybe the docs should mention a little bit more that with `javadoc` the `javadoc` binary from JDK 9 is meant, not the `<release>9</release>` in a maven build.

Still, I can see an error:
```java
[WARNING] Javadoc Warnings
[WARNING] java.lang.IllegalStateException
[WARNING] at net.sourceforge.plantuml.svek.Bibliotekon.getShapeUid(Bibliotekon.java:125)
[WARNING] at net.sourceforge.plantuml.cucadiagram.Link.getEntityPort1(Link.java:251)
[WARNING] at net.sourceforge.plantuml.svek.Line.<init>(Line.java:225)
[WARNING] at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:369)
[WARNING] at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:100)
[WARNING] at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:66)
[WARNING] at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:427)
[WARNING] at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:179)
[WARNING] at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:196)
[WARNING] at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:130)
[WARNING] at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:153)
[WARNING] at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:125)
[WARNING] at nl.talsmasoftware.umldoclet.uml.Diagram.renderDiagramFile(Diagram.java:169)
[WARNING] at nl.talsmasoftware.umldoclet.uml.Diagram.render(Diagram.java:129)
[WARNING] at nl.talsmasoftware.umldoclet.UMLDoclet$$Lambda$325.00000000CC1AB590.accept(Unknown Source)
[WARNING] at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$326.00000000CC1A90A0.accept(Unknown Source)
[WARNING] at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[WARNING] at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[WARNING] at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[WARNING] at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[WARNING] at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
[WARNING] at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[WARNING] at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
[WARNING] at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:739)
[WARNING] at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[WARNING] at nl.talsmasoftware.umldoclet.UMLDoclet.run(UMLDoclet.java:130)
[WARNING] at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582)
[WARNING] at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431)
[WARNING] at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
[WARNING] at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[WARNING] at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
[WARNING] java.lang.IllegalStateException
[WARNING] at net.sourceforge.plantuml.svek.Bibliotekon.getShapeUid(Bibliotekon.java:125)
[WARNING] at net.sourceforge.plantuml.cucadiagram.Link.getEntityPort1(Link.java:251)
[WARNING] at net.sourceforge.plantuml.svek.Line.<init>(Line.java:225)
[WARNING] at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:369)
[WARNING] at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:100)
[WARNING] at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:66)
[WARNING] at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:427)
[WARNING] at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:179)
[WARNING] at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:196)
[WARNING] at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:130)
[WARNING] at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:153)
[WARNING] at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:125)
[WARNING] at nl.talsmasoftware.umldoclet.uml.Diagram.renderDiagramFile(Diagram.java:169)
[WARNING] at nl.talsmasoftware.umldoclet.uml.Diagram.render(Diagram.java:129)
[WARNING] at nl.talsmasoftware.umldoclet.UMLDoclet$$Lambda$325.00000000CC1AB590.accept(Unknown Source)
[WARNING] at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$326.00000000CC1A90A0.accept(Unknown Source)
[WARNING] at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[WARNING] at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[WARNING] at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[WARNING] at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[WARNING] at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
[WARNING] at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[WARNING] at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
[WARNING] at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:739)
[WARNING] at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[WARNING] at nl.talsmasoftware.umldoclet.UMLDoclet.run(UMLDoclet.java:130)
[WARNING] at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582)
[WARNING] at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431)
[WARNING] at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
[WARNING] at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[WARNING] at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
```

Also, on a server with 32 cores it takes 11 minutes to build, whereas locally it only takes 50 seconds. But the error can be seen on both server and my laptop, which means this is not the cause.

I use adopt-openj9@1.11.0-5 from https://adoptopenjdk.net/ -- maybe PlantUML was never tested on non-hotspot-VMs?

**Comment by sjoerdtalsma** [comment]
> Yes, it works like a charm now.

Great to hear it works! 🎉 

> Luckily I did. Maybe the docs should mention a little bit more that with javadoc the javadoc binary from JDK 9 is meant, not the <release>9</release> in a maven build.

Good point; if you would like to contribute, I would definitely welcome a pull request that clarifies this. If you don't have the time however, feel free to open an issue instead so we won't forget about this clarification.

> Still, I can see an error:

I ran into something that sounds similar; please check the following links if they could help you:
- #184
- https://forum.plantuml.net/9781/invocationtargetexception-fileformat-getjavadimension
- https://github.com/AdoptOpenJDK/openjdk-docker/issues/75

> Also, on a server with 32 cores it takes 11 minutes to build, whereas locally it only takes 50 seconds. But the error can be seen on both server and my laptop, which means this is not the cause.
>
> I use adopt-openj9@1.11.0-5 from https://adoptopenjdk.net/ -- maybe PlantUML was never tested on non-hotspot-VMs?

😳 I run it on adoptopenjdk all the time. 50 seconds versus 11 minutes is crazy! I understand that your software is closed source but I'm getting curious about this huge difference.

**Comment by bmarwell** [comment]
> > Also, on a server with 32 cores it takes 11 minutes to build, whereas locally it only takes 50 seconds. But the error can be seen on both server and my laptop, which means this is not the cause.
> >
> > I use adopt-openj9@1.11.0-5 from https://adoptopenjdk.net/ -- maybe PlantUML was never tested on non-hotspot-VMs?
> 
> 😳 I run it on adoptopenjdk all the time. 50 seconds versus 11 minutes is crazy! I understand that your software is closed source but I'm getting curious about this huge difference.


Ok, to have this documented. AdoptOpenJDK is now Temurin and AdoptOpenJDK-OpenJ9 is now IBM Semeru with OpenJ9. Both are now available from adoptium.

Now, the build time was caused by "link references", but on my CI I had a firewall active and ran into a lot of very long timeouts.

Furthermore, compiling your own graphviz etc should usually not be needed. Most distributions come with expat support included.

**Comment by sjoerdtalsma** [comment]
Thanks for the follow-up!
